name: Jenkins

on: push

jobs:
  jenkins:
    name: jenkins code base
    runs-on: linux-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Jenkins
        uses: github/jenkins@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
